version: "3"
services:
  
  treinoml-db:
    image: postgres:9.6
    container_name: "treinomldb"
    environment:
      POSTGRES_DB: "treinomldb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      TZ: "GMT"
    volumes:
      - '/home/ruibraz/dev/postgres/treinomldb:/var/lib/postgresql/data'
    ports:
      - "5433:5432"
    networks: 
      - postgres-treinomldb

  pgadmin4:
    image: dpage/pgadmin4:4.10
    container_name: "pgadmin4"
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "secret"
    ports: 
      - "8082:80"
    networks: 
      - pgadmin
    
networks: 
  postgres-treinomldb:
  pgadmin:
